---
- name: Test collection example on zilux.tempie.message collection/role
  hosts: localhost
  become: false
  vars:
    sat_host: pipo

  tasks:

    - name: INCLUDE Using role from collection
      ansible.builtin.include_role:
        name: zilux.tempie.message
      tags:
        - in 
