---
- name: Test collection example on zilux.tempie.message collection/role
  hosts: localhost
  become: false
  vars:
    sat_host: pipo

  tasks:

    - name: Using role from collection
      ansible.builtin.import_role:
        name: zilux.tempie.message
